version: 2.1
orbs:
  python: circleci/python@2.0.3
  docker: circleci/docker@2.1.2
  heroku: circleci/heroku@1.2.6
jobs:
  build_test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run Tests
          command: python manage.py test
      - run:
          name : Run Linting
          command: flake8 --max-line-length=119
  

  build-image:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:$CIRCLE_SHA1 .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-image:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:$CIRCLE_SHA1
  build_push:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Package app and push to DockerHub
          command: |

  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - setup_remote_docker
      - run:
          name: Deploy to Heroku
          command: |
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a ${HEROKU_APP_NAME} web
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a ${HEROKU_APP_NAME} web
workflows:
  build_master:
    jobs:
      - build_test:
          filters:
            branches:
              only: master
      - build_push:
          requires:
            - build_test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build_push
          filters:
            branches:
              only: master
  build_other_branches:
    jobs:
      - build_test:
          filters:
            branches:
              ignore: master
