version: 2.1
orbs:
  python: circleci/python@2.0.3
  docker: circleci/docker@2.1.2
  heroku: circleci/heroku@1.2.6
jobs:
  build_test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run Tests
          command: pytest
      - run:
          name : Run Linting
          command: flake8
  build_push:
    docker:
      - image: cimg/python:3.10
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - run:
          name: Build And Push Docker Image
          command: |
            TAG=0.0.$CIRCLE_BUILD_NUM
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin
            docker build -t $DOCKER_LOGIN/oc_lettings:$TAG .
            docker tag $DOCKER_LOGIN/oc_lettings:$TAG $DOCKER_LOGIN/oc_lettings:latest
            docker push $DOCKER_LOGIN/oc_lettings:$TAG
            docker push $DOCKER_LOGIN/oc_lettings:latest
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - setup_remote_docker
      - run:
          name: Deploy to Heroku
          command: |
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a ${HEROKU_APP_NAME} web
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a ${HEROKU_APP_NAME} web
workflows:
  build_master:
    jobs:
      - build_test:
          filters:
            branches:
              only: master
      - build_push:
          requires:
            - build_test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build_push
          filters:
            branches:
              only: master
  build_other_branches:
    jobs:
      - build_test:
          filters:
            branches:
              ignore: master
