# Generated by Django 4.0.6 on 2022-11-22 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='letting',
            options={'verbose_name_plural': 'Lettings'},
        ),
    ]
